### ISSUE TITLE
IDEA: move image generation to GHA, and image storage to GHCR

### ISSUE THREAD

**Issue by urschrei** [georust/docker-images#30]
The Dockerfiles we build aren't especially complex and Docker – with its various team / org / resource restrictions – isn't my favourite service to use. Given that there are high-quality actions available for building images and that we only use the images in Github, is it worth exploring this? I like the idea of driving everything from an action using a `libproj_version` x `rust_version` matrix.

**Comment by michaelkirk** [comment]
> I like the idea of driving everything from an action using a libproj_version x rust_version matrix.

That sounds great. The current build system is something kludged together over time and I wouldn't be sad to see it go, so long as it remains easy to specify a range of rust versions and proj version.

Supporting more than one proj version at a time with the build system would be a new feature, so I don't view it as necessary, but sure, it might be nice if it's easy!

**Comment by urschrei** [comment]
The matrix is actually more of a vector (I only foresee the latest libproj) in practice!
